export const DEMO_LINES = [
  "Tell me about a time you had to debug a complex production issue.",
  "What was the root cause, and how did you investigate it systematically?",
  "How did you communicate status updates to your team during the incident?",
];

export const DEMO_ANSWER =
  "Start with structured incident response — establish a timeline and reproduce in staging if possible. For root cause I use five-whys to get past symptoms to the underlying cause. Communication-wise, a dedicated channel with 15-30 minute updates keeps stakeholders informed without pulling engineers out of flow. Post-resolution, a blameless postmortem builds shared knowledge and prevents recurrence.";

const LEADERSHIP_AND_EXECUTIVE_ROLES = [
  "Founder",
  "Co-Founder",
  "Owner",
  "Partner",
  "Managing Director",
  "President",
  "Chief Executive Officer",
  "Chief Operating Officer",
  "Chief Financial Officer",
  "Chief Technology Officer",
  "Chief Product Officer",
  "Chief Information Officer",
  "Chief Marketing Officer",
  "Chief Human Resources Officer",
  "Chief Commercial Officer",
  "Chief Revenue Officer",
  "Chief Security Officer",
  "Vice President",
  "Senior Vice President",
  "Executive Vice President",
  "Head of Department",
  "Director",
  "Senior Director",
  "Associate Director",
  "General Manager",
  "Group Manager",
  "Manager",
  "Senior Manager",
  "Team Lead",
  "Lead",
  "Supervisor",
  "Principal",
  "Staff",
  "Senior",
  "Junior",
  "Associate",
  "Intern",
  "Trainee",
  "Apprentice",
];

const TECHNOLOGY_ROLES = [
  "Software Engineer",
  "Frontend Engineer",
  "Backend Engineer",
  "Full Stack Engineer",
  "Mobile Engineer",
  "iOS Engineer",
  "Android Engineer",
  "Desktop Engineer",
  "Embedded Software Engineer",
  "Firmware Engineer",
  "Platform Engineer",
  "Infrastructure Engineer",
  "DevOps Engineer",
  "Site Reliability Engineer",
  "Cloud Engineer",
  "Systems Engineer",
  "Network Engineer",
  "Database Administrator",
  "Database Engineer",
  "Security Engineer",
  "Application Security Engineer",
  "DevSecOps Engineer",
  "Solutions Architect",
  "Enterprise Architect",
  "Technical Architect",
  "Data Engineer",
  "Analytics Engineer",
  "Data Scientist",
  "Machine Learning Engineer",
  "AI Engineer",
  "MLOps Engineer",
  "Research Engineer",
  "QA Engineer",
  "Quality Assurance Engineer",
  "Test Automation Engineer",
  "SDET",
  "Performance Engineer",
  "Release Engineer",
  "Build Engineer",
  "Technical Program Manager",
  "Product Analyst",
  "Business Analyst",
  "Systems Analyst",
  "Implementation Engineer",
  "Support Engineer",
  "Technical Support Engineer",
  "IT Support Specialist",
  "Help Desk Technician",
  "IT Manager",
  "Developer Advocate",
  "Technical Writer",
];

const PRODUCT_AND_DESIGN_ROLES = [
  "Product Manager",
  "Associate Product Manager",
  "Senior Product Manager",
  "Lead Product Manager",
  "Product Owner",
  "Product Director",
  "VP of Product",
  "Product Designer",
  "Senior Product Designer",
  "UX Designer",
  "Senior UX Designer",
  "UI Designer",
  "Interaction Designer",
  "Visual Designer",
  "Motion Designer",
  "Graphic Designer",
  "Brand Designer",
  "Content Designer",
  "UX Researcher",
  "Design Researcher",
  "Service Designer",
  "Accessibility Specialist",
  "Web Designer",
  "Design System Designer",
  "Design Director",
  "Creative Director",
  "Art Director",
  "Copywriter",
  "UX Writer",
  "Illustrator",
  "Animator",
  "Industrial Designer",
  "Interior Designer",
];

const DATA_AND_ANALYTICS_ROLES = [
  "Data Analyst",
  "Senior Data Analyst",
  "Business Intelligence Analyst",
  "BI Developer",
  "Analytics Analyst",
  "Analytics Manager",
  "Reporting Analyst",
  "Data Visualization Specialist",
  "Data Quality Analyst",
  "Data Governance Analyst",
  "Business Analyst",
  "Research Analyst",
  "Market Research Analyst",
  "Product Analyst",
  "Operations Analyst",
  "Financial Analyst",
  "Senior Financial Analyst",
  "Quantitative Analyst",
  "Statistician",
  "Data Steward",
  "Data Architect",
];

const OPERATIONS_AND_PROJECT_ROLES = [
  "Operations Manager",
  "Operations Analyst",
  "Business Operations Manager",
  "Business Operations Analyst",
  "Project Manager",
  "Program Manager",
  "Portfolio Manager",
  "Scrum Master",
  "Agile Coach",
  "PMO Manager",
  "Process Improvement Manager",
  "Chief of Staff",
  "Office Manager",
  "Administrative Assistant",
  "Executive Assistant",
  "Operations Coordinator",
  "Operations Supervisor",
  "Supply Chain Manager",
  "Logistics Coordinator",
  "Warehouse Manager",
  "Inventory Manager",
  "Procurement Specialist",
  "Purchasing Manager",
  "Facilities Manager",
  "Chief Operating Officer",
];

const SALES_AND_CUSTOMER_ROLES = [
  "Sales Representative",
  "Inside Sales Representative",
  "Outside Sales Representative",
  "Account Executive",
  "Account Manager",
  "Sales Manager",
  "Sales Director",
  "Sales Engineer",
  "Solutions Engineer",
  "Business Development Representative",
  "Business Development Manager",
  "Channel Sales Manager",
  "Customer Success Manager",
  "Customer Success Specialist",
  "Customer Support Specialist",
  "Customer Support Manager",
  "Customer Onboarding Specialist",
  "Sales Operations Analyst",
  "Revenue Operations Manager",
  "Partnerships Manager",
  "Community Manager",
  "Client Relations Manager",
];

const MARKETING_AND_MEDIA_ROLES = [
  "Marketing Manager",
  "Digital Marketing Manager",
  "Product Marketing Manager",
  "Brand Manager",
  "Growth Manager",
  "Demand Generation Manager",
  "Performance Marketing Manager",
  "Marketing Operations Manager",
  "Marketing Analyst",
  "Content Strategist",
  "Content Marketer",
  "Copywriter",
  "SEO Specialist",
  "SEM Specialist",
  "Social Media Manager",
  "Email Marketing Manager",
  "Campaign Manager",
  "Event Manager",
  "Public Relations Manager",
  "Communications Manager",
  "PR Specialist",
  "Media Buyer",
  "Creative Strategist",
  "Editor",
  "Journalist",
  "Reporter",
  "Broadcast Journalist",
  "Producer",
  "Video Producer",
  "Podcaster",
  "Content Creator",
];

const FINANCE_AND_ACCOUNTING_ROLES = [
  "Accountant",
  "Senior Accountant",
  "Bookkeeper",
  "Auditor",
  "Payroll Specialist",
  "Payroll Manager",
  "Tax Specialist",
  "Tax Manager",
  "Financial Analyst",
  "Senior Financial Analyst",
  "Finance Manager",
  "Financial Controller",
  "Controller",
  "Treasury Analyst",
  "FP&A Analyst",
  "Budget Analyst",
  "Credit Analyst",
  "Risk Analyst",
  "Risk Manager",
  "Investment Analyst",
  "Investment Banker",
  "Portfolio Manager",
  "Actuary",
  "Chief Financial Officer",
];

const PEOPLE_AND_HR_ROLES = [
  "HR Manager",
  "HR Generalist",
  "HR Business Partner",
  "People Operations",
  "People Partner",
  "Recruiter",
  "Technical Recruiter",
  "Senior Recruiter",
  "Talent Acquisition Specialist",
  "Sourcer",
  "Compensation Analyst",
  "Benefits Specialist",
  "Learning and Development Manager",
  "Training Specialist",
  "Talent Development Manager",
  "Organizational Development Manager",
  "Employee Relations Specialist",
  "Workforce Planning Analyst",
  "HR Coordinator",
  "Payroll Manager",
  "Diversity and Inclusion Manager",
  "Chief Human Resources Officer",
];

const LEGAL_AND_COMPLIANCE_ROLES = [
  "Lawyer",
  "Attorney",
  "Corporate Counsel",
  "Legal Counsel",
  "Paralegal",
  "Legal Assistant",
  "Legal Operations Manager",
  "Compliance Officer",
  "Compliance Analyst",
  "Contract Manager",
  "Risk and Compliance Manager",
  "Policy Analyst",
  "Privacy Officer",
  "Data Protection Officer",
  "Regulatory Affairs Specialist",
  "Ethics Officer",
];

const HEALTHCARE_AND_LIFE_SCIENCES_ROLES = [
  "Doctor",
  "Physician",
  "General Practitioner",
  "Surgeon",
  "Nurse",
  "Registered Nurse",
  "Licensed Practical Nurse",
  "Nurse Practitioner",
  "Physician Assistant",
  "Medical Assistant",
  "Medical Coder",
  "Pharmacist",
  "Pharmacy Technician",
  "Clinical Research Coordinator",
  "Clinical Trial Manager",
  "Clinical Research Associate",
  "Laboratory Technician",
  "Biomedical Engineer",
  "Radiologist",
  "Sonographer",
  "Therapist",
  "Physical Therapist",
  "Occupational Therapist",
  "Speech-Language Pathologist",
  "Psychologist",
  "Counselor",
  "Social Worker",
  "Dietitian",
  "Nutritionist",
  "Dentist",
  "Dental Hygienist",
  "Optometrist",
  "Veterinarian",
  "Veterinary Technician",
  "Public Health Specialist",
  "Healthcare Administrator",
  "Hospital Administrator",
  "Respiratory Therapist",
  "Emergency Medical Technician",
  "Paramedic",
];

const EDUCATION_AND_ACADEMIA_ROLES = [
  "Teacher",
  "Substitute Teacher",
  "Professor",
  "Associate Professor",
  "Assistant Professor",
  "Lecturer",
  "Tutor",
  "Academic Advisor",
  "School Counselor",
  "Principal",
  "Vice Principal",
  "Dean",
  "Registrar",
  "Librarian",
  "Instructional Designer",
  "Curriculum Developer",
  "Education Coordinator",
  "Special Education Teacher",
  "Training Specialist",
  "Research Assistant",
  "Admissions Counselor",
];

const TRADES_AND_MANUFACTURING_ROLES = [
  "Architect",
  "Civil Engineer",
  "Structural Engineer",
  "Mechanical Engineer",
  "Electrical Engineer",
  "Industrial Engineer",
  "Construction Manager",
  "Site Supervisor",
  "Foreman",
  "Carpenter",
  "Electrician",
  "Plumber",
  "Welder",
  "Machinist",
  "CNC Operator",
  "Production Supervisor",
  "Manufacturing Engineer",
  "Quality Inspector",
  "Maintenance Technician",
  "Safety Officer",
  "Surveyor",
  "Drafter",
  "Metal Fabricator",
  "Boiler Operator",
  "HVAC Technician",
  "Millwright",
  "Auto Mechanic",
  "Tool and Die Maker",
  "Industrial Designer",
  "Packaging Engineer",
];

const HOSPITALITY_AND_RETAIL_ROLES = [
  "Store Manager",
  "Assistant Store Manager",
  "Retail Associate",
  "Sales Associate",
  "Merchandiser",
  "Buyer",
  "Cashier",
  "Visual Merchandiser",
  "Retail Buyer",
  "Restaurant Manager",
  "Assistant Restaurant Manager",
  "Chef",
  "Sous Chef",
  "Line Cook",
  "Pastry Chef",
  "Baker",
  "Server",
  "Bartender",
  "Barista",
  "Host",
  "Hotel Manager",
  "Front Desk Agent",
  "Concierge",
  "Housekeeping Supervisor",
  "Housekeeper",
  "Travel Agent",
  "Event Coordinator",
  "Catering Manager",
  "Tour Guide",
  "Airline Customer Service Agent",
  "Flight Attendant",
];

const PUBLIC_SECTOR_AND_SAFETY_ROLES = [
  "Civil Servant",
  "Public Policy Analyst",
  "Policy Advisor",
  "Government Relations Manager",
  "City Planner",
  "Urban Planner",
  "Transportation Planner",
  "Program Officer",
  "Grant Writer",
  "Diplomat",
  "Foreign Service Officer",
  "Intelligence Analyst",
  "Police Officer",
  "Detective",
  "Firefighter",
  "Emergency Management Specialist",
  "Parole Officer",
  "Correctional Officer",
  "Military Officer",
  "Logistics Officer",
  "Public Administrator",
  "Tax Inspector",
  "Social Policy Analyst",
];

const AGRICULTURE_AND_ENVIRONMENT_ROLES = [
  "Farmer",
  "Farm Manager",
  "Agricultural Scientist",
  "Agronomist",
  "Horticulturist",
  "Botanist",
  "Environmental Scientist",
  "Environmental Engineer",
  "Sustainability Manager",
  "Renewable Energy Engineer",
  "Energy Analyst",
  "Geologist",
  "Hydrologist",
  "Water Resource Engineer",
  "Conservation Scientist",
  "Wildlife Biologist",
  "Park Ranger",
  "Ecologist",
  "Soil Scientist",
  "Forestry Technician",
];

const SCIENCE_AND_RESEARCH_ROLES = [
  "Research Scientist",
  "Research Analyst",
  "Research Assistant",
  "Laboratory Manager",
  "Laboratory Technician",
  "Chemist",
  "Biologist",
  "Microbiologist",
  "Geneticist",
  "Physicist",
  "Mathematician",
  "Statistician",
  "Biotech Researcher",
  "Materials Scientist",
  "Neuroscientist",
  "Epidemiologist",
  "Toxicologist",
  "Pharmacologist",
  "Archaeologist",
  "Anthropologist",
  "Sociologist",
  "Economist",
  "Quantitative Researcher",
];

export const JOB_ROLES = Array.from(
  new Set([
    ...LEADERSHIP_AND_EXECUTIVE_ROLES,
    ...TECHNOLOGY_ROLES,
    ...PRODUCT_AND_DESIGN_ROLES,
    ...DATA_AND_ANALYTICS_ROLES,
    ...OPERATIONS_AND_PROJECT_ROLES,
    ...SALES_AND_CUSTOMER_ROLES,
    ...MARKETING_AND_MEDIA_ROLES,
    ...FINANCE_AND_ACCOUNTING_ROLES,
    ...PEOPLE_AND_HR_ROLES,
    ...LEGAL_AND_COMPLIANCE_ROLES,
    ...HEALTHCARE_AND_LIFE_SCIENCES_ROLES,
    ...EDUCATION_AND_ACADEMIA_ROLES,
    ...TRADES_AND_MANUFACTURING_ROLES,
    ...HOSPITALITY_AND_RETAIL_ROLES,
    ...PUBLIC_SECTOR_AND_SAFETY_ROLES,
    ...AGRICULTURE_AND_ENVIRONMENT_ROLES,
    ...SCIENCE_AND_RESEARCH_ROLES,
  ])
);

export const SHORTCUTS: [string, string][] = [
  ["Start / Stop Listening", "Alt+Q"],
  ["Get Answer", "Alt+W"],
  ["Analyze Screen", "Alt+Enter"],
  ["Scroll to Bottom", "Alt+Down"],
  ["Clear", "Alt+C"],
  ["Toggle App", "Alt+X"],
  ["Move App Left", "Ctrl+Shift+Left"],
  ["Move App Right", "Ctrl+Shift+Right"],
];
